package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Tuesday, 28 March, 2023 2:52:27 PM IST
*/

public interface CalculatorOperations 
{
  float add (float num1, float num2);
  float subtract (float num1, float num2);
  float multiply (float num1, float num2);
  float divide (float num1, float num2);
} // interface CalculatorOperations
